Update SlackTextFileCore.java
seeing these fields can be null while fetching conversationHistory for a given channel
error: Cannot build SlackCsvFile, some of required attributes are not set [editLink, preview, previewHighlight, lines, linesMore, previewTruncated]